### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by davidbelich** [CodeKoalas/koality-drupal-theme-generator#5]
![issue](https://user-images.githubusercontent.com/43216841/46412298-bf0d5d00-c6e3-11e8-8131-e7603ebd6116.jpeg)

**Comment by fabean** [comment]
@davidbelich What version of node are you running? `node -v` Works for me on v10+

**Comment by fabean** [comment]
@davidbelich Run `npm update -g generator-koality-theme` to get on version 2.0.3 of this generator then try again.
